language: php

php:
  - 7.0.2

services:
  - mysql

before_script:
  - composer install
  - mysql -e 'create database appdb_test;'

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover
